sudo: required

language: php

services:
  - docker

before_install:
  - docker --version
  - pip install --user awscli # Install the AWS CLI
  - export PATH=$PATH:HOME/.local/bin # Put the AWS CLI in the path
  - docker build -t ecr-hello-world . # Build the docker image
  - docker run -d -p 8080 ecr-hello-world # Ensure that it runs
  - docker ps -a

script:
  - eval $(aws ecr get-login --region ${AWS_ECR_REPO_REGION}) # Log into the ECR repository.
  - docker tag ecr-hello-world:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REPO_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}:latest
  - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_ECR_REPO_REGION}.amazonaws.com/${AWS_ECR_REPO_NAME}:latest
